- name: "Update Repository cache"
  apt:
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true
  become: yes

- name: Install required system packages
  apt:
    pkg:
      - unzip
    state: latest
    update_cache: true

# Já baixado
#- name: Baixando o cliente AWS
#  shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#  become: yes
#  ignore_errors: yes
#  register: out
#- debug: var=out.stdout_lines

# Não testado
#- name: Giving permissions to replace awscli files if needed
#  shell: chmod -R +d /home/ubuntu/aws
#  become: yes
#  ignore_errors: yes
#  register: out
#- debug: var=out.stdout_lines

# Já instalado
#- name: Installing the client
#  expect:
#    command: unzip awscliv2.zip
#    responses:
#      "replace aws/install? [y]es, [n]o, [A]ll, [N]one, [r]ename:": "A"
#  become: yes
#  register: out
#- debug: var=out.stdout_lines

- name: Instalando o cliente AWS
  shell: "./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli"
  become: yes
  ignore_errors: yes
  register: out
- debug: var=out.stdout_lines

- name: Validando o cliente AWS
  shell: "aws --version"
  ignore_errors: yes
  register: out
- debug: var=out.stdout_lines
